"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_gold)\
$os\
[](bg:color_purple fg:color_gold)\
$directory\
[](fg:color_purple bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_light_grey)\
$docker_context\
$conda\
[](fg:color_light_grey bg:color_grey)\
$time\
[ ](fg:color_grey)\
$line_break$character"""

palette = 'majoras_mask'

[palettes.majoras_mask]
color_white = '#f9f1f1'
color_grey = '#3c3836'
color_light_grey = '#665c54'
color_purple = '#4b3970'
color_orange = '#bc503c'
color_red = '#ff0000'
color_gold = '#d79921'
color_yellow = '#f4ee75'
color_green = '#67913b'
color_blue = '#2e5978'


[os]
disabled = false
style = "bg:color_gold fg:color_white"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰯙"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "fg:color_white bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_white bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_white bg:color_green)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
version_format = '${major}.${minor}'
format = '[[ $symbol( $version) ($virtualenv) ](fg:color_white bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_light_grey"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_light_grey)]($style)'

[conda]
style = "bg:color_light_grey"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_light_grey)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_grey"
format = '[[  $time ](fg:color_white bg:color_grey)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_orange)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_gold)'
